### ISSUE TITLE
Carbon Coop Report Formatting Comments - Important

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#241] opened 2017-02-23 16:21 UTC
These are general comments on formatting of the report. They're about readability and interpretation, so they probably take priority over the printing thing at the moment (which is in any case almost there!)

Typo - at 'Summary of Section 3.0' should read "we've also included **six** appendices" (not five)

GRAPHS: 

1. Text for graph title and axis labels needs to be bolder/darker and bigger. Currently not very readable when printed. 
2. Y-axes values need to be consistent - at the moment they re-size when different data is added. This is affecting how easy it is to compare graphs between assessments (which is useful to be able to do), is giving a misleading impression of scale, and means you sometimes get odd divisions (so rather than labels at 100, 200 etc, you get 80, 120, 160). Also means you lose the 'UK Average' markers if someone's energy use is already quite low. 
3. Need to be enough markers on Y-axis to be able to make sense of the graph - this may relate to point above and be sorted by fixing the axis, but for e.g. only marker on Figure 9 on one assessment is at 1000kg. Not that helpful. In Figure 8 the y-axis numbers have disappeared completely. 

Figure 4: Can we add some text to the legend to make it clearer. 'Internal _Gains_', 'Solar _Gains_', 'Space Heating _Requirement_', 'Fabric _Losses_', 'Ventilation and Infiltration _Losses_'

Figure 13: Boxes relating to draughts not showing? 

Figure 14: Under 'You also told us', need to be able to distinguish better between the subject/ question and the response - at the moment each one reads as a single block of text, which is confusing. Perhaps italicise response? 

Figures 15/16/17
 - Where we have a measure that applies to the whole house - like draught-proofing or ventilation - in the label/location column it is showing as undefined. Can we change this to show as 'whole house'. (No way for me to add this at the moment in the Library). 
- Where the label/location for a measure has got very long (for example where batch apply measures has been done on windows) it throws off the whole table format. Need to be able to shorten this here - perhaps just when a label gets over a certain character count, shorten it to 'various'.

**Comment by cagabi** [comment] 2017-03-02 20:06
Ok this is all done. Coments

**Graphs**
I have done the y axis consistent but I think you should check the max values I have put:
- Heat balance: +-250 kWh/m2.year
- Space heating demand: 200 kWh/m2.year
- Energy Demand: 35000 kWh/year
- Primary Energy Use: 400 kWh/m2.year
- Carbon Dioxide Emissions: 80 kgCO2/m2.year
- Carbon Dioxide Emissions Per Person: 8000 kgCO2/person/year
- Estimate Energy Costs (Net) Comparison: 3100 £/year

The reason why I want to check is because of the Carbon Dioxide Emissions Per Person which in Vicar's road is around 7500 while in 63 Nicholas is around 3000. I don't know which are realistic figures

**Boxes relating to draughts not showing**
The only way I can replicate the problem is creating a new assessment and not clicking in the household questionnaire. In this case the qustionaire is _empty_ and nothing was showing. In this case I have added a text saying _There is not enough information, please check section 3 in Household Questionnaire._ The same applies to _You also told us_

**Figures 15/16/17**
In that case Appendix A was also displaying the annoyinng _,br_. Not anymore

**Comment by marianneURBED** [comment] 2017-03-03 17:22
Hi Carlos, 

That all looks better - I'll print next week and check, and also check the values for the y-axis. 

Slight problem - something seems to have broken in doing this so in Ali's report I've lost:
 -  all of the measures tables (short, long and comparison tables)
 - some of the information from the householder questionnaire (questions on loved/unloved rooms etc). 

If this is gone for good, I can just re-do the data entry on a fresh assessment - however it's probably worth checking this isn't being caused by an error in the code before I do. 

I'll share the assessment with you so you can see.

Thanks, 

Marianne

**Comment by cagabi** [comment] 2017-03-10 11:26
As per phone text conversation: measures are there so problem may have been due to transitional breakage of the tool by Carlos

**Comment by marianneURBED** [comment] 2017-03-23 16:05
Hello, 

Max/min values need to be as follows (have just been through and chacked the results for the last 2 years of real assessments - vicars rd not real!

Heat balance: +-250 kWh/m2.year > OK
Space heating demand: 200 kWh/m2.year > change to 250, at 50kWh increments
Energy Demand: 35000 kWh/year > change to 40,000, at 5000 kWh increments
Primary Energy Use: 400 kWh/m2.year > change to 500, at 50kWh increments. 
Carbon Dioxide Emissions: 80 kgCO2/m2.year > change to 100, at 10kg increments. 
Carbon Dioxide Emissions Per Person: 8000 kgCO2/person/year > OK
Estimate Energy Costs (Net) Comparison: 3100 £/year > change to £3500, at £500 increments. 

Thanks.

**Comment by cagabi** [comment] 2017-03-24 12:10
Done

**Comment by cagabi** [comment] 2017-07-31 14:38
From Marianne's email:

> Also - some of the graphs are proving not to be that useful as this house uses so much energy - we may have to adjust the scales on the graphs to make them more useful. If this is still the case once the PV has been added in to the modelled results, may need some help from Carlos. Not sure whether to make this a permanent change - will depend on how much of an outlier this house is because of its size and heating system.

I can easily keep the graphs as they are now with a fixed max value, which was the original requirement on this issue, but increase the max value for those cases when we go over

**Comment by cagabi** [comment] 2017-07-31 15:11
I thought it made lots of sense, so I have done as said in my previous message.
I close the issue now but feel free to reopen it

**Closed by cagabi** 2017-07-31 15:11 UTC
Labels: For release, Needed for report, Very high priority
