### ISSUE TITLE
Changing Overshading to Rooflight doesn't change solar gain

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#237] opened 2017-02-17 17:00 UTC
Will share the assessment with you carlos

**Comment by marianneURBED** [comment] 2017-02-23 16:56
I'm having the same issue.

**Comment by cagabi** [comment] 2017-03-08 18:50
I found it!!!!! This is not a bug, this is a very accurate implementation of SAP2012: the overshading is not taken into account when calculating the solar gains for roof lights. Difficult to believe but so it is.

**6.1 Solar gains for openings (p. 22):** 
Gsolar = 0.9 x A x S x gl x FF x Z
A = area of opening
S = solar flux
gl = glazing factor
FF =  frame factor
Z = solar access factor

**Solar access factor table 6d (p.26) note 2**
A solar access factor of 1.0 [...] should be used for roof lights

**Comment by gervasemangwana** [comment] 2017-03-08 19:16
Somehow I thought this may be the case. Thanks for your ever vigilant hunting Carlos. Through you I learned the deepest corners of SAP. 
You can see there point. But also. You know. Big trees. 

G

**Comment by marianneURBED** [comment] 2017-03-23 09:36
Ok. So I think we change this so all windows, including rooflights, use the same calculation for solar access factor. Will have only a minimal effect in most cases - but for e.g., it risks rewarding putting heavily over-shaded roof-lights on a property, which feels silly. 

Need to make a note of this deviation from SAP in the code and the manuals. 

Not going to make a massive difference to most assessments, so not a high priority to sort. Will mark it up as such. 

(Do you think this is one of the bits where the powerful 'rooflight' lobby have influenced SAP?)

**Comment by gervasemangwana** [comment] 2017-03-23 11:33
That all sounds sensible. But let's hope the rooflight lobby don't catch wind of it.

**Comment by cagabi** [comment] 2017-03-23 14:13
As it was a very quick tweak, I have done it.

I have also added a little question mark to the "Over shading" header of the windows table saying _MHEP applies same solar access factor to roof lights than any other windows. This is a deviation from SAP2012 (p.26 note 2) where solar factors for roof lights are always 1 independently of the over shading_

If you like the text, please close the issue. If not send me another one.

**Comment by marianneURBED** [comment] 2017-03-23 14:18
Perfect. Thanks. Just a minor typo to fix. 

MHEP applies same solar access factor to roof lights *as* any other windows. This is a deviation from SAP2012 (p.26 note 2) where solar factors for roof lights are always 1 *independent* of the over shading

**Comment by cagabi** [comment] 2017-03-23 14:19
Yippiieeeeee!

**Closed by cagabi** 2017-03-23 14:19 UTC
Labels: Medium  priority
