### ISSUE TITLE
Floor U-value calculator not calculating

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#395] opened 2018-07-23 17:46 UTC
For suspended floors - enter all the figures and hit calculate but nothing happens. 

(Feel like this has happened before, but I couldn't find the old issue, in case it's the same problem. Sorry!)

**Comment by cagabi** [comment] 2018-07-24 15:11
If you have the moment can you please do it again and once the tool doesn't respond open the developer tools (roght click anywhere in screen) and copy the error that must be in the console.
Thanks

**Comment by marianneURBED** [comment] 2018-07-25 11:30
And here's the developer console. 
Seems to be returning the U-value of the walls as 'NaN' - guessing that's the problem?
<img width="1440" alt="screen shot 2018-07-25 at 12 28 53" src="https://user-images.githubusercontent.com/16305707/43198417-7a092536-9006-11e8-8c39-8d5e042719e1.png">

**Comment by cagabi** [comment] 2018-07-25 12:54
I have fixed it,
The problem was that I missed a parameter in the calculation of the equivalent thickness of the basement wall (generating a NotANumber (NaN) result). The error didn't show before because we only have to calculate it when the deepness of the basement floor is more than 0.5m

**Comment by cagabi** [comment] 2018-07-25 12:58
Trying it again and something different seems to be broken. Hold on before using it

**Comment by cagabi** [comment] 2018-07-25 15:33
The problem is not related to this so I close this issue again

**Closed by cagabi** 2018-07-25 15:33 UTC
Labels: Very high priority, bug
